// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using votingApp2.Models;

#nullable disable

namespace votingApp2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230301060523_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("votingApp2.Models.Options", b =>
                {
                    b.Property<int>("option_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<string>("option")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("owner_id")
                        .HasColumnType("int");

                    b.Property<int>("poll_id")
                        .HasColumnType("int");

                    b.HasKey("option_id");

                    b.HasIndex("poll_id");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("votingApp2.Models.Poll", b =>
                {
                    b.Property<int>("poll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("owner_id")
                        .HasColumnType("int");

                    b.HasKey("poll_id");

                    b.HasIndex("owner_id");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("votingApp2.Models.Votter", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("postal_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("telephone_number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("user_Id");

                    b.ToTable("Votters");
                });

            modelBuilder.Entity("votingApp2.Models.Options", b =>
                {
                    b.HasOne("votingApp2.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("poll_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("votingApp2.Models.Poll", b =>
                {
                    b.HasOne("votingApp2.Models.Votter", "Votter")
                        .WithMany("Poll")
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Votter");
                });

            modelBuilder.Entity("votingApp2.Models.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("votingApp2.Models.Votter", b =>
                {
                    b.Navigation("Poll");
                });
#pragma warning restore 612, 618
        }
    }
}
